spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/dolphintwo/spring-cloud-config
          search-paths: config-repo
          uri: https://gitee.com/dolphintwo/spring-cloud-config
server:
  port: 8888